/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvReviewIdRouteImport } from './routes/cv-review.$id'
import { Route as ApiReviewCvRouteImport } from './routes/api/review-cv'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvReviewIdRoute = CvReviewIdRouteImport.update({
  id: '/cv-review/$id',
  path: '/cv-review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewCvRoute = ApiReviewCvRouteImport.update({
  id: '/api/review-cv',
  path: '/api/review-cv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/review-cv': typeof ApiReviewCvRoute
  '/cv-review/$id': typeof CvReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/review-cv': typeof ApiReviewCvRoute
  '/cv-review/$id': typeof CvReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/review-cv': typeof ApiReviewCvRoute
  '/cv-review/$id': typeof CvReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/api/review-cv' | '/cv-review/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/api/review-cv' | '/cv-review/$id'
  id: '__root__' | '/' | '/history' | '/api/review-cv' | '/cv-review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ApiReviewCvRoute: typeof ApiReviewCvRoute
  CvReviewIdRoute: typeof CvReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-review/$id': {
      id: '/cv-review/$id'
      path: '/cv-review/$id'
      fullPath: '/cv-review/$id'
      preLoaderRoute: typeof CvReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-cv': {
      id: '/api/review-cv'
      path: '/api/review-cv'
      fullPath: '/api/review-cv'
      preLoaderRoute: typeof ApiReviewCvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ApiReviewCvRoute: ApiReviewCvRoute,
  CvReviewIdRoute: CvReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
